### PR TITLE
Update to 2.0.0rc9

### PR DESCRIPTION
**Pull request by jasongrout**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jasongrout** [comment]
@jtpio - I added you as a maintainer. Are you okay with that?

**Comment by jtpio** [comment]
Nice thanks, that sounds good :+1: 

I had opened #31 to update to 2.0.0rc9, but let's keep this one instead since it updates the jupyter_server dependency.

**Comment by jtpio** [comment]
Does the bot pick up new maintainers on the rc branch?

When we did it in the jupyterlab feedstock it didn't seem to be the case.

**Comment by jasongrout** [comment]
> I had opened #31 to update to 2.0.0rc9, but let's keep this one instead since it updates the jupyter_server dependency.

Sorry I missed that one.

**Comment by jasongrout** [comment]
> Does the bot pick up new maintainers on the rc branch?

I don't know. I'll put in a PR to the main branch just in case.

**Comment by jasongrout** [comment]
> I don't know. I'll put in a PR to the main branch just in case.

Actually, it will only be a few days until this is merged into master - that will be easier to just let this update propagate then.

**Pull request merged**
