### PR TITLE
jupyterlab_server 2.5.0, tests, coverage 

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- includes #46 
- adds tests with coverage threshold
  - currently blocked by https://github.com/conda-forge/staged-recipes/pull/14740

### CODE REVIEW

**Comment by bollwyvl** [comment]
Breaks as expected, but works locally-from-slightly-in-the-future:

```
import: 'jupyterlab_server'
import: 'jupyterlab_server'
+ pip check
No broken requirements found.
+ pytest -vv --pyargs jupyterlab_server --cov jupyterlab_server --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 59
============================= test session starts ==============================
platform linux -- Python 3.8.8, pytest-6.2.3, py-1.10.0, pluggy-0.13.1 -- $PREFIX/bin/python
cachedir: .pytest_cache
rootdir: $SRC_DIR
plugins: cov-2.11.1, anyio-2.2.0, console-scripts-1.2.0, tornasync-0.6.0.post2
collecting ... collected 23 items / 1 skipped / 22 selected

tests/test_labapp.py::test_lab_handler <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_labapp.py PASSED [  4%]
tests/test_labapp.py::test_notebook_handler <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_labapp.py PASSED [  8%]
tests/test_labapp.py::test_404 <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_labapp.py PASSED [ 13%]
tests/test_listings_api.py::test_get_listing <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_listings_api.py PASSED [ 17%]
tests/test_settings_api.py::test_get_settings <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_settings_api.py PASSED [ 21%]
tests/test_settings_api.py::test_get_federated <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_settings_api.py PASSED [ 26%]
tests/test_settings_api.py::test_get_bad <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_settings_api.py PASSED [ 30%]
tests/test_settings_api.py::test_listing <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_settings_api.py PASSED [ 34%]
tests/test_settings_api.py::test_patch <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_settings_api.py PASSED [ 39%]
tests/test_settings_api.py::test_patch_unicode <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_settings_api.py PASSED [ 43%]
tests/test_settings_api.py::test_patch_wrong_id <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_settings_api.py PASSED [ 47%]
tests/test_settings_api.py::test_patch_bad_data <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_settings_api.py PASSED [ 52%]
tests/test_settings_api.py::test_patch_invalid_payload_format <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_settings_api.py PASSED [ 56%]
tests/test_settings_api.py::test_patch_invalid_json <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_settings_api.py PASSED [ 60%]
tests/test_themes_api.py::test_get_theme <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_themes_api.py PASSED [ 65%]
tests/test_workspaces_api.py::test_delete <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_workspaces_api.py PASSED [ 69%]
tests/test_workspaces_api.py::test_get_non_existant <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_workspaces_api.py PASSED [ 73%]
tests/test_workspaces_api.py::test_get <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_workspaces_api.py PASSED [ 78%]
tests/test_workspaces_api.py::test_listing <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_workspaces_api.py PASSED [ 82%]
tests/test_workspaces_api.py::test_listing_dates <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_workspaces_api.py PASSED [ 86%]
tests/test_workspaces_api.py::test_put <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_workspaces_api.py PASSED [ 91%]
tests/test_workspaces_api.py::test_bad_put <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_workspaces_api.py PASSED [ 95%]
tests/test_workspaces_api.py::test_blank_put <- ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/tests/test_workspaces_api.py PASSED [100%]

=============================== warnings summary ===============================
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyter_server/services/config/manager.py:17
  $PREFIX/lib/python3.8/site-packages/jupyter_server/services/config/manager.py:17: DeprecationWarning: metadata {'default': 'serverconfig'} was set from the constructor. With traitlets 4.1, metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
    config_dir_name = Unicode(

../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/jupyterlab_server/app.py:31
  $PREFIX/lib/python3.8/site-packages/jupyterlab_server/app.py:31: DeprecationWarning: metadata {'default': '2.5.0'} was set from the constructor. With traitlets 4.1, metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
    app_version = Unicode('', help='The version of the application.',

-- Docs: https://docs.pytest.org/en/stable/warnings.html

----------- coverage: platform linux, python 3.8.8-final-0 -----------
Name                                                                                                                                                                                                                                                                                                                                        Stmts   Miss  Cover   Missing
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/__init__.py                         7      1    86%   21
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/__main__.py                         3      3     0%   2-5
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/app.py                             40      6    85%   73-88
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/config.py                         168     63    62%   30-36, 47-65, 94-102, 118-139, 147-154, 159-164, 181-182, 251, 263, 283, 300, 307-318
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/handlers.py                       144     16    89%   51-52, 100, 155, 157, 218-220, 228, 230, 235-241, 247-249
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/listings_handler.py                40     17    58%   22-29, 31-38, 77
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/process.py                        150    150     0%   2-289
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/process_app.py                     27     27     0%   2-46
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/pytest_plugin.py                   60      4    93%   94, 109, 123, 135
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/settings_handler.py               216     33    85%   48, 54-56, 63-65, 94-95, 102-104, 143-144, 162, 194, 200, 225, 246-247, 252-253, 263, 268-269, 310, 342-343, 360, 376, 383, 392-393
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/tests/test_translation_api.py     146    132    10%   31-245
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/tests/utils.py                     99     27    73%   38, 61, 121-135, 142-146, 152, 154-156, 161-170
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/themes_handler.py                  43     31    28%   23-37, 46-50, 54-58, 62-87
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/translation_utils.py              211    165    22%   46-55, 75-84, 91-105, 124-132, 159-168, 187-190, 209-227, 245-277, 305-335, 354-385, 396-399, 411-421, 437, 457, 475, 497, 514, 534, 552, 574, 594-595, 607-611, 630-636, 640
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/translations_handler.py            36     21    42%   40-50, 56, 70-90
$PREFIX/lib/python3.8/site-packages/jupyterlab_server/workspaces_handler.py             118     18    85%   28, 43-44, 106, 116, 122, 128-129, 147-152, 165-168, 177-178
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                                                                                                                                                                                                                                                        1752    714    59%

9 files skipped due to complete coverage.

Required test coverage of 59% reached. Total coverage: 59.25%
================== 23 passed, 1 skipped, 2 warnings in 3.36s ===================
+ exit 0

Resource usage statistics from testing jupyterlab_server:
   Process count: 3
   CPU time: Sys=0:00:00.1, User=0:00:02.8
   Memory: 80.2M
   Disk usage: 132B
   Time elapsed: 0:00:06.2


```

**Comment by bollwyvl** [comment]
bummer about `tests/test_translation_api.py`, but I guess we can't ship it because windows path length.

**Comment by blink1073** [comment]
Kicking CI

**Comment by blink1073** [comment]
Ah, `openapi-core` isn't available just yet: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=309707&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=153

**Comment by bollwyvl** [comment]
Up, but waiting for CDN... https://anaconda.org/conda-forge/openapi-core

**Comment by blink1073** [comment]
File is up, kicking...

**Comment by bollwyvl** [comment]
Up, but not on CDN, so not widely distributed. I'm monitoring, will kick when it's ready.

For reference, here's the script i have in the root of my `conda-forge` junk that i use:

```bash
#!/usr/bin/env bash
set -eux
wget -N https://conda-static.anaconda.org/conda-forge/rss.xml || echo "no change"
tail -n100 rss.xml \
	| grep "$@"
```

invoked with:

```bash
watch -n60 'bash _cdn.sh openapi'
```

The RSS feed gets deployed with the updated repodata, so it ain't true until it says so. It is, however, a titanic file (being XML with lots of timestamps), so the `-n60` makes me not look like some evil bot. I should probably figure out a way to do range headers based on how much data i do already have from `wget -N`....

**Comment by bollwyvl** [comment]
@conda-forge/jupyterlab_server ready for review! I'm _much_ less grumpy about automerge when checks like these are in-place.

**Pull request merged**
